export const en = {
    title: "An online platform to buy tickets for streaming concerts of your favorite artists",
    website: "website",
    repository: "Repository",
    first_title: "Henryfy: A Melodic E-commerce",
    first_description: "Henryfy is a web application, born in the labs stage of the bootcamp Henry, as a goal we had to build a platform where you could listen to music from your favorite artists while buying tickets for their concerts by streaming.",
    developed_with: "It was developed with:",
    registration_title: "Registration and Login System",
    registration_description: "It has a registration system, where you put your personal data and a profile picture, with that same data you can log in to your account, and start buying.",
    guest_title: "Shopping as Guest User",
    guest_description: "Although we also have a guest system where you can choose products and take them to your shopping cart, and see the total amount and quantity of products you are buying",
    checkout_description: "To checkout and make the payment, you must log in to finalize your purchase. Payments are simulated and are made through the Stripe platform.",
    categories_title: "Categories",
    categories_description: "The concert tickets are divided into categories, there are many, among them Reggaeton, Hip Hop, Salsa, Bachata, Rock, Tango, etc. And you can filter and see which ones are available for purchase and if a product is not available because it is sold out, you will also see it.",
    product_details: "Product Details",
    product_details_description: "You can also enter to see details of the tickets you are going to buy, such as the price, reviews of users who have purchased, an average rating and you can listen to a song of the artist if you don't know him and you are interested! We have a section for you to listen to a song of that artist on Youtube.",
    edit_profile: "Edit Profile",
    edit_profile_description: "You can also edit your user data, such as your email, password, first name, last name, etc.",
    administrator: "Administrator User",
    administrator_description: "If you log in the site as an administrator, you have access to data such as how many users are registered on the platform, how many products there are in total, what were the last purchase orders and the reviews of all the users!",
    reviews_title: "Reviews Form",
    reviews_description: "If you bought a product on our site, you can also give us feedback on whether you liked the purchase process, if you liked the event, or any recommendations you would like to give us."
}

export const es = {
    title: "Plataforma online para comprar tickets de conciertos por streaming de tus artistas favoritos",
    website: "Website",
    repository: "Repositorio",
    first_title: "Henryfy: Un E-commerce Melódico",
    first_description: "Henryfy es una aplicación web, nacida en la etapa Labs del bootcamp de Henry, como meta, teníamos construir una plataforma donde puedas escuchar canciones de tus artistas favoritos mientras compras tickets para sus conciertos por streaming.",
    developed_with: "Fue desarrollado con:",
    registration_title: "Sistema de Registro e Inicio de Sesión",
    registration_description: "Cuenta con un sistema de registro donde colocas tus datos personales en un formulario, junto con una foto de perfil, con los mismos datos puedes iniciar sesión y empezar a comprar",
    guest_title: "Comprar como Invitado",
    guest_description: "Si no estás registrado, al entrar estás como usuario invitado, puedes agregar productos a tu carrito y ver el total y el monto de los productos que estás comprando",
    checkout_description: "Para finalizar tu compra y realizar el pago, deberás iniciar sesión. Los pagos son simulados y son hechos a través de la plataforma Stripe.",
    categories_title: "Categorías",
    categories_description: "Los tickets de los conciertos están divididos en categorías, hay muchas, como Reggaeton, Hip Hop, Salsa, Bachata, Rock, Tango, etc. Y puedes filtrar y ver cuáles están disponibles para comprar y si el producto no está disponible porque se agotó, también lo podrás visualizar.",
    product_details: "Detalle de Productos",
    product_details_description: "También puedes entrar a ver el detalle de los tickets que vas a comprar, como el precio, reseñas de los usuarios que ya compraron, el promedio de las calificaciones y puedes escuchar una canción de ese artista si no le conoces y te interesa. Tenemos una sección para que escuches una canción de ese artista en Youtube.",
    edit_profile: "Editar Perfil",
    edit_profile_description: "Puedes editar tus datos, como email, contraseña, nombre, apellido, etc.",
    administrator: "Usuario Administrador",
    administrator_description: "Si inicias sesión como administrador, tienes acceso a datos como cuántos usuarios hay registrados, cuántos productos tenemos en total, cuál fue la última orden de compra y las reseñas que han dejado los usuarios",
    reviews_title: "Formulario de Reseñas",
    reviews_description: "Si compraste un producto con nosotros, nos puedes dar tu opinión sobre el proceso de compra,  la atención, si te gustó el evento o cualquier comentario que tengas para mandarnos."
}