export const en = {
    title: "A comfortable fintech app to manage your money",
    demo: "Demo",
    repository: "Repository",
    friendly_app: "MOBA: A Friendly Banking App",
    friendly_app_description: "MOBA is a mobile app, born in the labs stage of the bootcamp Henry, as a goal we had to build an app where we simulate the basic operation of a banking app, where you can transfer money between users of the same app, charge money to your account, transfer money to unregistered users and include interoperability to operate with users of another banking app developed in the same labs process (Tree Bank) It was developed with:",
    languages: "React Native, Redux, Sequelize, Postgres and Express Gateway for Microservices",
    designed: "And designed with:",
    title_register: "Registration and Login System",
    register_description: "We have a registration system where you need to validate your email before you can go to the register form, we send an email with an unique code, and with that code you can advance",
    add_money_title: "Add Money",
    add_money_description: "To add money you have the option of recharge your account with a unique code, or you can copy your number account to clipboard or share it via whatsapp",
    statistics: "Statistics",
    statistics_description: "You can see all your movements in the statistics section, from the last week to 6 months ago",
    virtual_card: "Virtual Card",
    virtual_card_description: "Here you can see your virtual card, and copy to clipboard the number card if you want to insert it into a shopping form",
    transactions_title: "Transactions",
    transactions_description: "To make a transfer to another MOBA user, you have to add it to your contact list, then you can transfer any amount to that contact, and see the receipt transfer and share it via whatsapp or via mail",
    transfer_unregister: "Transfer to Unregistered Users And Interoperability",
    transfer_unregister_description: "You can also make a transfer to an user that doesn't have an account in our app, we will send a mail to register to the app, and when your contact sign up his account, he will have your transfer!",
    transfer_unregister_description_2: "In the Henry Labs another banking app was developed, the name of that app is Tree Bank and we can send money to that app with a number account of some user of that app!"
}

export const es = {
    title: "Una app cómoda para manejar tu dinero",
    demo: "Demo",
    repository: "Repositorio",
    friendly_app: "MOBA: Una Fintech App Amigable",
    friendly_app_description: "MOBA es una app móvil, nacida en la etapa Labs del bootcamp Henry, como meta teníamos construir una app donde simularamos las operaciones básicas de un banco, donde exista la posibilidad de transferir dinero entre usuarios de la misma app, cargar dinero a tu cuenta, transferir dinero a usuarios no registrados e incluimos interoperabilidad para transferir dinero a usuarios de otra fintech app que se estaba desarrollando tambien en Henry Labs (Tree Bank) Fue desarrollada con:",
    languages: "React Native, Redux, Sequelize, Postgres y Express Gateway para los Microservicios",
    designed: "Y diseñada con:",
    title_register: "Sistema de Registro e Inicio de Sesión",
    register_description: "Tenemos un sistema de registro donde tienes que validar tu email antes de poder seguir con el formulario de registro, mandamos un mail con un código único, y cuando lo validas, puedes avanzar",
    add_money_title: "Agregar Dinero",
    add_money_description: "Para añadir dinero, tienes la opción de recargar tu cuenta con un código único, puedes copiar tu número de cuenta o compartirlo por whatsapp",
    statistics: "Estadísticas",
    statistics_description: "Puedes ver todos tus movimientos en la sección de estadísticas, desde la última semana hasta los últimos 6 meses",
    virtual_card: "Tarjeta Virtual",
    virtual_card_description: "Aquí puedes ver tu tarjeta virtual (se genera el crear tu cuenta), y puedes copiar el número de tarjeta para luego insertarlo en algún formulario de compra",
    transactions_title: "Transferencias",
    transactions_description: "Para hacer una transferencia a otro usuario MOBA, tienes que añadirlo a tu lista de contactos, luego puedes transferir cualquier monto a ese contacto, al hacerla, puedes ver el recibo de transferencia y compartirlo por whatsapp",
    transfer_unregister: "Transferencias a Usuarios No Registrados e Interoperabilidad",
    transfer_unregister_description: "Puedes transferir también a usuarios no registrados en nuestra app, le mandaremos un email a esa persona para que se registre en nuestra app, y cuando se registre va a tener disponible el monto que le transferiste!",
    transfer_unregister_description_2: "En Henry Labs otra Fintech App fue creada también, su nombre es Tree Bank y puedes mandar dinero a un usuario de esa app mediante el CVU (número de cuenta)"
}